{
  apkType: 2,
  contentRating: ['Everyone 10+', 'Fantasy Violence'],
  category: 'GAME_STRATEGY',
  description: 'Enter the Arena! From the creators of Clash of Clans comes a real-time multiplayer game starring the Royales, your favorite Clash characters and much, much more.<br><br>Collect and upgrade dozens of cards featuring the Clash of Clans troops, spells and defenses you know and love, as well as the Royales: Princes, Knights, Baby Dragons and more. Knock the enemy King and Princesses from their towers to defeat your opponents and win Trophies, Crowns and glory in the Arena. Form a Clan to share cards and build your very own battle community.<br><br>Lead the Clash Royale Family to victory!<br><br>PLEASE NOTE! Clash Royale is free to download and play, however, some game items can also be purchased for real money. If you do not want to use this feature, please set up password protection for purchases in the settings of your Google Play Store app. Also, under our Terms of Service and Privacy Policy, you must be at least 13 years of age to play or download Clash Royale.<br><br>A network connection is also required.<br><br>FEATURES<br>● Duel players from around the world in real-time and take their Trophies<br>● Earn chests to unlock rewards, collect powerful new cards and upgrade existing ones<br>● Destroy opponent’s towers and win Crowns to earn epic Crown chests<br>● Build and upgrade your card collection with the Clash Royale Family along with dozens of your favorite Clash troops, spells and defenses<br>● Construct your ultimate Battle Deck to defeat your opponents<br>● Progress through multiple Arenas all the way to the top<br>● Form a Clan to share cards and build your very own battle community<br>● Challenge your Clanmates and friends to a private duel<br>● Learn different battle tactics by watching the best duels on TV Royale<br><br><br>Support<br>Are you having problems? Visit http://supercell.helpshift.com/a/clash-royale/ or http://supr.cl/ClashRoyaleForum or contact us in game by going to Settings &gt; Help and Support.<br><br>Privacy Policy: <br>http://supercell.com/en/privacy-policy/<br><br>Terms of Service:<br>http://supercell.com/en/terms-of-service/<br><br>Parent’s Guide:<br>http://supercell.com/en/parents/',
  developer: 'Supercell',
  descriptionShort: 'Enter the Arena! From the creators of Clash of Clans comes a real-time multiplayer game starring the Royales, your favorite Clash characters and much, much more.\r\n\r\nCollect and upgrade dozens of cards featuring the Clash of Clans troops, spells and defenses you know and love, as well as the Royales: Princes, Knights, Baby Dragons and more. Knock the enemy King and Princesses from their towers to defeat your opponents and win Trophies, Crowns and glory in the Arena. Form a Clan to share cards and build your very own battle community.\r\n\r\nLead the Clash Royale Family to victory!\r\n\r\nPLEASE NOTE! Clash Royale is free to download and play, however, some game items can also be purchased for real money. If you do not want to use this feature, please set up password protection for purchases in the settings of your Google Play Store app. Also, under our Terms of Service and Privacy Policy, you must be at least 13 years of age to play or download Clash Royale.\r\n\r\nA network connection is also required.\r\n\r\nFEATURES\r\n● Duel players from around the world in real-time and take their Trophies\r\n● Earn chests to unlock rewards, collect powerful new cards and upgrade existing ones\r\n● Destroy opponent’s towers and win Crowns to earn epic Crown chests\r\n● Build and upgrade your card collection with the Clash Royale Family along with dozens of your favorite Clash troops, spells and defenses\r\n● Construct your ultimate Battle Deck to defeat your opponents\r\n● Progress through multiple Arenas all the way to the top\r\n● Form a Clan to share cards and build your very own battle community\r\n● Challenge your Clanmates and friends to a private duel\r\n● Learn different battle tactics by watching the best duels on TV Royale\r\n\r\n\r\nSupport\r\nAre you having problems? Visit http://supercell.helpshift.com/a/clash-royale/ or http://supr.cl/ClashRoyaleForum or contact us in game by going to Settings > Help and Support.\r\n\r\nPrivacy Policy: \r\nhttp://supercell.com/en/privacy-policy/\r\n\r\nTerms of Service:\r\nhttp://supercell.com/en/terms-of-service/\r\n\r\nParent’s Guide:\r\nhttp://supercell.com/en/parents/',
  descriptionTranslation: '',
  developerId: '6715068722362591614',
  developerLink: [{
      name: 'Visit website',
      href: 'http://supercell.helpshift.com/a/clash-royale/'
    },
    {
      name: 'gp-info@supercell.com',
      href: 'mailto:gp-info@supercell.com'
    }
  ],
  detailUrl: 'https://play.google.com/store/apps/details?gl=us&hl=en&id=com.supercell.clashroyale',
  img: ['https://lh3.googleusercontent.com/UMcUoOIPw9__JjZn3Wg-Q-xBFlTRw6EVw70gk5m5kfkBjjzrdEPhhr-MF1egnZRpTktm',
    'https://lh3.googleusercontent.com/hXImEoedPGzNP5QskFpHEVV4IOJjUI_XG7AC5g57dBKG882tLUge005zU1cAJnRmfPGD',
    'https://lh3.googleusercontent.com/d9XGHEBeYVNL5-Hlnv_FsStWR2W1UCPimGGivGF6_Vck45VvejdN7W2o1X2kRD3CTEj6',
    'https://lh3.googleusercontent.com/XMsIhyyM8W-qO-vXbhWc7K2Wkn45LwdbIg8mBBZHuWsmP51zJesAnzi4SK0C4Qd-NQ',
    'https://lh3.googleusercontent.com/wpl60c9iouTyhLGrumtYFajuFVCs84fr5pPWxLlUQ4HjbH5mRxxLkyle70NrqI6cHLE',
    'https://lh3.googleusercontent.com/JqlmxJPS4be8f-aWMQiG-xqFhJYtD4CZ3x6Jvu_yJKnwnAsYbLaaZJKqQ-1wKkh2AQ',
    'https://lh3.googleusercontent.com/k4ofyzRCSM5YeY6UjqDRCrQOJ3pYFuJ0Ie0-faN72_HkWxi4oRQAaUoq5wJWlISjHQ',
    'https://lh3.googleusercontent.com/FHvtoVRHoZNM8R_Gpe_0Kllb_qgJ5_MJ4r-nAqD1IwfCz2soCa2VuqVgMOMH3OLj7A',
    'https://lh3.googleusercontent.com/ENFOzb81aaVl4e8qZZBtqhVOZcYUXV1x1hHD63HQ6XBS_xQD2qMd57MCSobr2veHfQ',
    'https://lh3.googleusercontent.com/5zqqQUy43o56knIoPHOn_7MSQVkBvhejBHPX21w0A-bw2ibN8hGl0uw23SDSWDDfAoU',
    'https://lh3.googleusercontent.com/IKryVYaKRlX7JHReMJ0qNtLTxkHBYQEK4EYXbT21a5E49laz2eBIQ_h_Pien4cLosxgQ',
    'https://lh3.googleusercontent.com/IvWXbFx9r4WIRPTPSKo1j5pg82r1Lstu5cTfBjsRl-KM4MeBvQqZcnIcM4eOqftmY_lF',
    'https://lh3.googleusercontent.com/cRs_aqW9QxrI1MYtZCIYuw5tBBGVEbr2HzzyfLs1pdVJtOUvjQqj_h7TuX-eL8JZS5w-',
    'https://lh3.googleusercontent.com/RU2ZmhVW4aKnW2bO1erk-VCrzR69Zyln-dgyP0LpiTplpXFFz04vTrRoDDGvpmkGbT0',
    'https://lh3.googleusercontent.com/K31DtLg3XUrNhZVDcT3VXJX4sn9UWjxtjEfMV8S639CuRhyozz6rmD9scAtOuzJtUQt7',
    'https://lh3.googleusercontent.com/aGgL62Ly-ifIj_l-6mGc8FRy3UAuxtiMJaEEC7yFzB1wrZhbcBtDeH5Yh9f0fNb_G3jB',
    'https://lh3.googleusercontent.com/bIqJtC67iRIq8cYbGyjuR5pm7_L0E3qUK58vygpqWyi5NcHHpQvrYDirXbOjk4nqfVQ',
    'https://lh3.googleusercontent.com/MpKTJrA28V6Cf3fZtKh8u0iouxtV2gK_9X_svefuykGBjB1360165UIGVjRJF_EdcA'
  ],
  icon: 'https://lh3.googleusercontent.com/K-MNjDiO2WwRNwJqPZu8Wd5eOmFEjLYkEEgjZlv35hTiua_VylRPb04Lig3YZXLERvI',
  installCount1: 0,
  installCount2: 0,
  interactiveElements: ['Users Interact', ' Digital Purchases'],
  inAppProducts: '$0.99 - $99.99 per item',
  name: 'Clash Royale',
  price: 0,
  packageName: 'com.supercell.clashroyale',
  reviewStars: '4.6',
  reviewCount: 21787686,
  reviewStarsSearch: '',
  published: true,
  publishedDate: 'April 25,2018',
  tube: 'https://www.youtube.com/embed/tNLvTCfsdjA?ps=play&vq=large&rel=0&autohide=1&showinfo=0',
  tubeId: 'tNLvTCfsdjA',
  translationBar: '',
  update: 1524644122000,
  versionDescription: '',
  versionSize: '97M',
  versionCurrentVersion: '2.2.1',
  versionRequiresAndroid: '4.0.3 and up',
  isAdsSupported: false,
  isAlpha: false,
  preRegister: '',
  wishList: '',
  inAppOffersPurchases: true,
  title: '',
  subTitle: '',
  gpInstallCount: '100,000,000+',
  html: '',
  developerEmail: 'gp-info@supercell.com',
  developerWebsite: 'http://supercell.helpshift.com/a/clash-royale/',
  developerAddress: 'Itamerenkatu 11-13\n00180 Helsinki\nFinland',
  recentChangesHtml: 'CLAN WARS IS HERE!<br>• Battle with your Clan against Clans from around the world<br>• Earn War Chests and glory!<br>• Discover a new island and the Clan Wars Arena<br>• Gain Clan Trophies to climb the Clan Leagues<br>• Is your Clan ready?',
  videoImage: 'https://i.ytimg.com/vi/tNLvTCfsdjA/hqdefault.jpg'
}