{
    apkType: 1,
    contentRating: ['Everyone', undefined],
    category: ['COMMUNICATION'],
    description: 'Google Chrome is a fast, easy to use, and secure web browser. Designed for Android, Chrome brings you personalized news articles, quick links to your favorite sites, downloads, and Google Search and Google Translate built-in. Download now to enjoy the same Chrome web browser experience you love across all your devices.<br>        <br>        <b>Browse fast and type less.</b> Choose from personalized search results that instantly appear as you type and quickly browse previously visited web pages. Fill in forms quickly with Autofill.<br>        <br>        <b>Incognito Browsing.</b> Use Incognito mode to browse the internet without saving your history. Browse privately across all your devices.<br>        <br>        <b>Sync Chrome Across Devices.</b> When you sign into Chrome, your bookmarks, passwords, and settings will be automatically synced across all your devices. You can seamlessly access all your information from your phone, tablet, or laptop.<br>        <br>        <b>All your favorite content, one tap away.</b> Chrome is not just fast for Google Search, but designed so you are one tap away from all your favorite content. You can tap on your favorite news sites or social media directly from the new tab page. Chrome also has the “Touch to Search”- feature on any webpage. You can tap on any word or phrase to start a Google search while still in the page you are enjoying.<br>        <br>        <b>Protect your phone with Google Safe Browsing.</b> Chrome has Google Safe Browsing built-in. It keeps your phone safe by showing warnings to you when you attempt to navigate to dangerous sites or download dangerous files.<br>        <br>        <b>Fast downloads and view web pages and videos offline</b> Chrome has a dedicated download button, so you can easily download videos, pictures, and entire webpages with just one tap. Chrome also has downloads home right inside Chrome, where you can access all the content you downloaded, even when you are offline.<br>        <br>        <b>Google Voice Search.</b> Chrome gives you an actual web browser you can talk to. Use your voice to find answers on-the-go without typing and go hands free. You can browse and navigate quicker using your voice anywhere, anytime.<br>        <br>        <b>Google Translate built-in: Quickly translate entire web pages.</b> Chrome has Google Translate built in to help you to translate entire web to your own language with one tap.<br>        <br>        <b>Save Mobile Data.</b> Turn on Chrome’s Data Saver to browse and navigate the web while using less data. Save up to 60% of data as Chrome compresses text, images, videos and websites without lowering the quality.<br>        <br>        <b>Smart personalized recommendations.</b> Chrome creates an experience that is tailored to your interests.  On the new tab page, you will find articles that Chrome selected based on your previous browsing history.',
    developer: 'Google LLC',
    descriptionShort: 'Google Chrome is a fast, easy to use, and secure web browser. Designed for Android, Chrome brings you personalized news articles, quick links to your favorite sites, downloads, and Google Search and Google Translate built-in. Download now to enjoy the same Chrome web browser experience you love across all your devices.\r\n        \r\n        Browse fast and type less. Choose from personalized search results that instantly appear as you type and quickly browse previously visited web pages. Fill in forms quickly with Autofill.\r\n        \r\n        Incognito Browsing. Use Incognito mode to browse the internet without saving your history. Browse privately across all your devices.\r\n        \r\n        Sync Chrome Across Devices. When you sign into Chrome, your bookmarks, passwords, and settings will be automatically synced across all your devices. You can seamlessly access all your information from your phone, tablet, or laptop.\r\n        \r\n        All your favorite content, one tap away. Chrome is not just fast for Google Search, but designed so you are one tap away from all your favorite content. You can tap on your favorite news sites or social media directly from the new tab page. Chrome also has the “Touch to Search”- feature on any webpage. You can tap on any word or phrase to start a Google search while still in the page you are enjoying.\r\n        \r\n        Protect your phone with Google Safe Browsing. Chrome has Google Safe Browsing built-in. It keeps your phone safe by showing warnings to you when you attempt to navigate to dangerous sites or download dangerous files.\r\n        \r\n        Fast downloads and view web pages and videos offline Chrome has a dedicated download button, so you can easily download videos, pictures, and entire webpages with just one tap. Chrome also has downloads home right inside Chrome, where you can access all the content you downloaded, even when you are offline.\r\n        \r\n        Google Voice Search. Chrome gives you an actual web browser you can talk to. Use your voice to find answers on-the-go without typing and go hands free. You can browse and navigate quicker using your voice anywhere, anytime.\r\n        \r\n        Google Translate built-in: Quickly translate entire web pages. Chrome has Google Translate built in to help you to translate entire web to your own language with one tap.\r\n        \r\n        Save Mobile Data. Turn on Chrome’s Data Saver to browse and navigate the web while using less data. Save up to 60% of data as Chrome compresses text, images, videos and websites without lowering the quality.\r\n        \r\n        Smart personalized recommendations. Chrome creates an experience that is tailored to your interests.  On the new tab page, you will find articles that Chrome selected based on your previous browsing history.',
    descriptionTranslation: '',
    developerId: '5700313618786177705',
    developerLink: [{
            name: 'Visit website',
            href: 'http://www.google.com/chrome/android'
        },
        {
            name: 'apps-help@google.com',
            href: 'mailto:apps-help@google.com'
        }
    ],
    detailUrl: 'https://play.google.com/store/apps/details?gl=us&hl=en&id=com.android.chrome',
    img: ['https://lh3.googleusercontent.com/lKPDNfsO2QhJD9i77rGDTiH5ILjXlXwPsRi194hhkY4BsbaXbpCFrdjWvcU1zttUwqXz',
        'https://lh3.googleusercontent.com/oRtDV6erbg6FrHN6yXeulEHhYNL5d4lhg1LPrT24XNEbHFEiJqmkiqtGt7VUSFDOc_U',
        'https://lh3.googleusercontent.com/jdPhSUb2TrrPki_GomuD3X2HZ_OSN25HTkDEX9pSFzNYu0id2p6JbOizRN8UDvGD5bY',
        'https://lh3.googleusercontent.com/B2qLmFjNUP6IVaorrgV-LWLclFH2o5jnfUmwEQQmK5QLMQvL8bJDIVL_fnTO0CqQmks',
        'https://lh3.googleusercontent.com/9nCLqQ0lKydGf-kTmzn6SuWaqBs5DOTLOLSYaZG1skCqtldACMjIbaIezkPqbcGcBA',
        'https://lh3.googleusercontent.com/reO-MkXk9XASNEH773Esw6tNHZQEmXJ7wyKNW8VLL89GAOQ81s12Trz3g-fc7HeYDA',
        'https://lh3.googleusercontent.com/GrjN1qUeJXUbkNuGa6_FQQqcOqLzd2rhy6l9VdpQSP3QIFrrPOUJ7f6RVIeDLF2s-HU',
        'https://lh3.googleusercontent.com/n-0iW1GyK3f8RsmivoVfVWgxK5NNFYKc4F_LCBRdl7QCqGHG79YuBz8V4Yg3A7asyCg',
        'https://lh3.googleusercontent.com/TupJ_ZSZrDR5NPH5wbtm5p39gEww0mZFffwKgihAenfSljkNzGnLckpRl8H7mBTjKoIU',
        'https://lh3.googleusercontent.com/KvVznTmYyTb5Wq46aGnAgqBJ3cLEkcm5Ws5osDMV6rhahmfbifb60BTBEPjJEVnx81B9',
        'https://lh3.ggpht.com/PY7G4R3S87Z6W10UMmPGaOCBB5-oER96IhC73tXRNKGNLmMDivUj6a43CxmUAcTY',
        'https://lh4.ggpht.com/q8v2wAOleQUEmH9Feu_gu2Bsa83KNj0QLhTy9Jcg4RjCnv_AuAlY2RmTtJYwCqfc2uA',
        'https://lh5.ggpht.com/BpMKDy12eJ29wG0wpJYoHekwkSvGb_660As07diH_JP4Rq6VEjmQyIXaaaCXcxq5WZc',
        'https://lh4.ggpht.com/6IaY7t3xdVMIfLMOi9ZPjwoeqIz4X6MfmP6rMTa2eVu9mdEdmWaV3QtutRRj0gkTTFA',
        'https://lh5.ggpht.com/jjsmaA6fHd4PMKcjgMHsXq0yksO9YleF1Gugp3zr2Wb9xjpr3wms7QFR8tX8-6i4Og'
    ],
    icon: 'https://lh3.googleusercontent.com/nYhPnY2I-e9rpqnid9u9aAODz4C04OycEGxqHG5vxFnA35OGmLMrrUmhM9eaHKJ7liB-',
    installCount1: 0,
    installCount2: 0,
    interactiveElements: ['Unrestricted Internet'],
    inAppProducts: undefined,
    name: 'Google Chrome: Fast & Secure',
    price: 0,
    packageName: 'com.android.chrome',
    reviewStars: '4.3',
    reviewCount: 9133117,
    reviewStarsSearch: '',
    published: true,
    publishedDate: 'April 25,2018',
    tube: undefined,
    tubeId: '',
    translationBar: '',
    update: 1524619969000,
    versionDescription: '',
    versionSize: 'Varies with device',
    versionCurrentVersion: 'Varies with device',
    versionRequiresAndroid: 'Varies with device',
    isAdsSupported: false,
    isAlpha: false,
    preRegister: '',
    wishList: '',
    inAppOffersPurchases: false,
    title: '',
    subTitle: '',
    gpInstallCount: '1,000,000,000+',
    html: '',
    developerEmail: 'apps-help@google.com',
    developerWebsite: 'http://www.google.com/chrome/android',
    developerAddress: '1600 Amphitheatre Parkway, Mountain View 94043',
    recentChangesHtml: 'Thanks for choosing Chrome! This release contains several new features:<br>• Set language preferences for web content in Settings &gt; Languages <br>• Turn on the prompt for simplified view for all supported articles in Settings &gt; Accessibility settings <br>• Share and delete downloads more easily on the Downloads page',
    videoImage: undefined
}