//多语言链接
var map = {
    key: 'ds:3',
    isError: false,
    hash: '13',
}
var data = [
    [
        true,
        "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dzh_CN",
        null, 
        [
            ["x-default", "/store/apps/details?id\u003dcom.catcto.jumping"],
            ["en-US",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003den_US"
            ],
            ["af",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003daf"
            ],
            ["am",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dam"
            ],
            ["ar",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dar"
            ],
            ["az",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003daz"
            ],
            ["be",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dbe"
            ],
            ["bg",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dbg"
            ],
            ["bn",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dbn"
            ],
            ["bs",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dbs"
            ],
            ["ca",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dca"
            ],
            ["cs",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dcs"
            ],
            ["da",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dda"
            ],
            ["de",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dde"
            ],
            ["de-AT",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dde_AT"
            ],
            ["de-CH",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dde_CH"
            ],
            ["el",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003del"
            ],
            ["en",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003den"
            ],
            ["en-AU",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003den_AU"
            ],
            ["en-CA",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003den_CA"
            ],
            ["en-GB",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003den_GB"
            ],
            ["en-IE",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003den_IE"
            ],
            ["en-IN",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003den_IN"
            ],
            ["en-SG",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003den_SG"
            ],
            ["en-ZA",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003den_ZA"
            ],
            ["es",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des"
            ],
            ["es-419",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_419"
            ],
            ["es-AR",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_AR"
            ],
            ["es-BO",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_BO"
            ],
            ["es-CL",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_CL"
            ],
            ["es-CO",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_CO"
            ],
            ["es-CR",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_CR"
            ],
            ["es-DO",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_DO"
            ],
            ["es-EC",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_EC"
            ],
            ["es-GT",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_GT"
            ],
            ["es-HN",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_HN"
            ],
            ["es-MX",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_MX"
            ],
            ["es-NI",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_NI"
            ],
            ["es-PA",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_PA"
            ],
            ["es-PE",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_PE"
            ],
            ["es-PR",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_PR"
            ],
            ["es-PY",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_PY"
            ],
            ["es-SV",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_SV"
            ],
            ["es-US",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_US"
            ],
            ["es-UY",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_UY"
            ],
            ["es-VE",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003des_VE"
            ],
            ["et",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003det"
            ],
            ["eu",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003deu"
            ],
            ["fa",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dfa"
            ],
            ["fi",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dfi"
            ],
            ["fil",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dfil"
            ],
            ["fr",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dfr"
            ],
            ["fr-CA",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dfr_CA"
            ],
            ["fr-CH",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dfr_CH"
            ],
            ["gl",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dgl"
            ],
            ["gsw",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dgsw"
            ],
            ["gu",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dgu"
            ],
            ["he",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003diw"
            ],
            ["hi",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dhi"
            ],
            ["hr",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dhr"
            ],
            ["hu",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dhu"
            ],
            ["hy",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dhy"
            ],
            ["id",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003din"
            ],
            ["is",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dis"
            ],
            ["it",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dit"
            ],
            ["ja",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dja"
            ],
            ["ka",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dka"
            ],
            ["kk",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dkk"
            ],
            ["km",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dkm"
            ],
            ["kn",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dkn"
            ],
            ["ko",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dko"
            ],
            ["ky",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dky"
            ],
            ["ln",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dln"
            ],
            ["lo",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dlo"
            ],
            ["lt",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dlt"
            ],
            ["lv",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dlv"
            ],
            ["mk",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dmk"
            ],
            ["ml",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dml"
            ],
            ["mn",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dmn"
            ],
            ["mr",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dmr"
            ],
            ["ms",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dms"
            ],
            ["my",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dmy"
            ],
            ["nb",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dnb"
            ],
            ["ne",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dne"
            ],
            ["nl",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dnl"
            ],
            ["no",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dno"
            ],
            ["pa",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dpa"
            ],
            ["pl",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dpl"
            ],
            ["pt",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dpt"
            ],
            ["pt-BR",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dpt_BR"
            ],
            ["pt-PT",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dpt_PT"
            ],
            ["ro",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dro"
            ],
            ["ru",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dru"
            ],
            ["si",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dsi"
            ],
            ["sk",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dsk"
            ],
            ["sl",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dsl"
            ],
            ["sq",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dsq"
            ],
            ["sr",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dsr"
            ],
            ["sr",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dsr_LATN"
            ],
            ["sv",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dsv"
            ],
            ["sw",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dsw"
            ],
            ["ta",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dta"
            ],
            ["te",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dte"
            ],
            ["th",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dth"
            ],
            ["tl",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dtl"
            ],
            ["tr",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dtr"
            ],
            ["uk",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003duk"
            ],
            ["ur",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dur"
            ],
            ["uz",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003duz"
            ],
            ["vi",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dvi"
            ],
            ["zh",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dzh"
            ],
            ["zh-CN",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dzh_CN"
            ],
            ["zh-HK",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dzh_HK"
            ],
            ["zh-TW",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dzh_TW"
            ],
            ["zu",
                "/store/apps/details/Jumping_LR?id\u003dcom.catcto.jumping\u0026hl\u003dzu"
            ]
        ]
    ]
]